// Targeted by JavaCPP version 1.4.3-SNAPSHOT: DO NOT EDIT THIS FILE

package wumo.sim;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class buf extends wumo.sim.presets.buf {
    static { Loader.load(); }

// Parsed from buf/library.h

// #ifndef BUF_LIBRARY_H
// #define BUF_LIBRARY_H

public static native void buf_init();

// #endif

}
